#Explorative data analysis
rm(list=ls())
getwd()
setwd("C:/Users/Fredrik.Augustsson/Documents/1.Analys/4.Coursera/1. Data Science/4. Exploratory Data Analysis")
getwd()
library(dplyr)
library(lubridate)
library(reshape2)
library(data.table)
list.files()
d<-data.table(read.csv2("household_power_consumption.txt", header=TRUE, stringsAsFactors = FALSE,  dec=".", sep=";"))
str(d1)
head(d)
tail(d)
class(d$Global_active_power)
d1<-filter(d, Date %in% c("1/2/2007","2/2/2007"))
d1$Global_active_power<-as.numeric(d1$Global_active_power)
d1$t<- strptime(paste(d1$Date, d1$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
png("plot2.png", width=480, height=480)
with(d1, plot(t, Global_active_power, type="l", xlab = "", ylab = "Global Active Power (kilowatts)"))
dev.off()

hist(d1$Global_active_power)
#d1<- d[d$Date %in% c("1/2/2007","2/2/2007") ,]
#d3<-filter(d, Date=="1/2/2007"| Date=="2/2/2007")